### ISSUE TITLE
Need to take credentials as input

### ISSUE THREAD

**Issue by akhilputhiry** [codementordev/cm-quiz#4]
The tool is not taking credentials or JWT token as input. Without credentials how would the tool will be able to hit the api and test the api server ?

**Comment by ocowchun** [comment]
The tool will hit create user API first before test any API that needs credentials, therefore it can obtain credentials when it receive create user API response. 😀

**Comment by akhilputhiry** [comment]
I didn't see the `users` API in the documentation. Need to scroll down to see that. I missed to add the users API and was rejected from codementor x :)
